# Generated by Django 2.1.1 on 2018-09-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=250)),
                ('token', models.CharField(blank=True, default='', max_length=250)),
                ('token_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField(choices=[(1, '1 pence'), (2, '2 pence'), (5, '5 pence'), (10, '10 pence'), (20, '20 pence'), (50, '50 pence'), (100, '1 pound'), (200, '2 pound'), (500, '5 pound'), (1000, '10 pound'), (2000, '20 pound'), (5000, '50 pound')], default=1, verbose_name='Currency unit')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount pcs')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Machine', to='app.Machine')),
            ],
        ),
    ]
